### ISSUE TITLE
Alternative license?

### ISSUE THREAD

**Issue by stephenfin** [ofosos/sphinxrecipes#1]
I've been working on [a spruce up of the Sphinx docs](https://github.com/sphinx-doc/sphinx/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Astephenfin+is%3Aclosed) over the past year or so. I spotted your excellent article on [opensource.com](https://opensource.com/article/18/11/building-custom-workflows-sphinx#comments) some time back and have finally started writing a tutorial for the actual Sphinx documentation based on it.

The tutorial itself will be mostly written from scratch (to keep it infitting with the other Sphinx docs) but I'd like to include the extension source almost verbatim from this repo (with full credits, of course).

This issue is that the Sphinx source is all BSD licensed and this appears to be GPL. IANAL but even if the extension is merely provided as an example, I don't think I can include the source as-is without introducing potential issues further down the line (copy and paste is awfully common).

Do you think it would be possible to (re-/dual-)license this repo with something like BSD or MIT so I could use that extension (again, with full credits) rather than writing this from scratch? If so, anything I can do to help?

**Comment by ofosos** [comment]
Yes, no problem. I'll update the license tomorrow (just returned from work).

**Comment by ofosos** [comment]
Thanks for the praise :)

**Comment by ofosos** [comment]
There you go. Ping me, when your tutorial is done.

**Comment by stephenfin** [comment]
Thanks! You can find the PR [here](https://github.com/sphinx-doc/sphinx/pull/6048). If you have a chance, please take a look and let me know if there's anything you think I missed. FWIW, the way I'm approaching the tutorials is to explain what we're doing along with some very high level overviews of the general concepts (things like domains, indices), but I'm leaving the more detailed overview of the concepts to another section of the docs.
