### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by bdice** [ofosos/sphinxrecipes#2]
I noticed that the license was updated in #1. Thanks for choosing a more permissive license! However, I'm very confused:

- The README still says "Licensed under GNU AGPL v3.0."
- The `setup.py` script says `license='GPLv3'`
- The commit message says "Re-license to BSD"
- The actual text of the `LICENSE` file is the MIT license.

Could you clarify the licensing? This is a really nice example code, I'm eager to use it in my work. 😃

**Comment by ofosos** [comment]
I'll fix it tomorrow, the intention is to have an mit license

**Comment by ofosos** [comment]
@bdice sorry, sometimes I'm slow. I wont correct the bad commit message, but I've changed all the other stuff. Hope that helps :)

**Comment by bdice** [comment]
@ofosos Thanks again!
